version: "3.4"

services:
  primepod:
    image: primepod
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn saleor.asgi:application --reload --host 0.0.0.0 --port 8000
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
    volumes:
      - ..:/app
    ports:
      - 8000:8000

  # dashboard:
  #   image: ghcr.io/saleor/saleor-dashboard:3.20.5
  #   restart: unless-stopped
  #   ports:
  #     - 9000:80

  redis:
    image: library/redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - saleor-redis:/data
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # Mailpit UI
    restart: unless-stopped

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  saleor-redis:
    driver: local
  redisinsight:
    driver: local
